#!/usr/bin/env ruby

require 'rack'
require File.dirname(__FILE__) + '/lib/simple_pvr'

Rack::Server.start(
  :config => SimplePvr::PvrInitializer.rackup_file_path,
  :Port => 4567,
  :server => 'puma'
)
