require 'bundler/setup'
require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'cucumber/rake/task'

directory 'output'

namespace :test do
  RSpec::Core::RakeTask.new(:spec)
  Cucumber::Rake::Task.new(:features)
end
  
desc 'Run specs and features'
task :test => ['test:spec', 'test:features']

task :default => ['test']